#!/usr/bin/env php
<?php
define('ATOMIC_START', microtime(true));
require __DIR__.'/vendor/autoload.php';
global $argv;

$app = require_once __DIR__.'/bootstrap/app.php';
$status = $app->handleCommand($argv);

exit($status);